repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: pretty-format-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/asottile/pyupgrade
  rev: v2.19.1
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs
  - id: remove-tabs
- repo: https://github.com/psf/black
  rev: 21.5b2
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.8.0
  hooks:
  - id: isort
