[tool.poetry]
name = "osr-stuff"
version = "0.1.0"
description = ""
authors = ["Andrew Herbig <notandrewherbig@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pygame = "^2.0.1"
recordclass = "^0.14.3"
Pillow = "^8.3.1"

[tool.poetry.dev-dependencies]
black = "^21.5b2"
flake8 = "^3.9.2"
pre-commit = "^2.13.0"
pyupgrade = "^2.21.2"
isort = "^5.9.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
